slogan: "å˜å®ä¸ºåºŸï¼Œå˜åºŸä¸ºæ ¸åºŸã€‚"

show_heart: false

show_slogan: true

menu:
  - title: ğŸ“ å­˜æ¡£
    url: archives
    intro: "å›æ”¶ï¼šæ—§å½©ç”µï¼Œæ—§å†°ç®±ï¼Œæ—§ç©ºè°ƒï¼Œæ—§åšå®¢â€”â€”"
    # icon: "fa fa-archive"
  - title: â“ å…³äº
    url: about
    intro: "å…³äºå¹ºè›¾å­å’Œå›æ”¶ç«™ã€‚"
    # icon: "fa fa-user"
  - title: ğŸ›œ RSS
    url: atom.xml
    intro: "ä¸€ç§ç¥å¥‡çš„è¿œå¤æŠ€æœ¯ã€‚"
    # icon: "fa-solid fa-rss"

links:
  - title: ğŸ“– GitHub
    url: https://github.com/talentedbug
    intro: "å¹ºè›¾å­çš„ GitHubã€‚"
    # icon: "fa fa-github"
  - title: âœ‰ï¸ é‚®ä»¶
    url: mailto:talentedbug@tutamail.com
    intro: "å¹ºè›¾å­çš„é‚®ä»¶ä¿¡ç®±ã€‚"
    # icon: "fa-solid fa-envelope"
  - title: ğŸ“¢ Reddit
    url: https://www.reddit.com/u/talentedbug
    intro: "å¹ºè›¾å­çš„ Redditã€‚"
    # icon: "fa-brands fa-reddit"
  - title: ğŸ“„ æ´›è°·
    url: https://www.luogu.com.cn/user/537285
    intro: "å¹ºè›¾å­çš„æ´›è°·ï¼ˆè’Ÿè’»ï¼‰ã€‚"
    # icon: "fa-solid fa-code"
  - title: ğŸš© Linux Do
    url: https://linux.do/u/talentedbug
    intro: "å¹ºè›¾å­çš„ Linux Doã€‚"
    # icon: "fa-solid fa-flag"

widgets:
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
